name: Deploy Affected APIs to Cloud Run

on:
  push:
    branches:
      - main
      - master

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  GAR_LOCATION: ${{ vars.GCP_REGION }}-docker.pkg.dev
  GAR_REPOSITORY: ${{ vars.GAR_REPOSITORY }}

jobs:
  # ##########################################################################
  # # JOB 1: DETERMINAR QUÉ APLICACIONES FUERON AFECTADAS
  # ##########################################################################
  determine-affected:
    name: Determine Affected Services
    runs-on: ubuntu-latest
    outputs:
      affected_matrix: ${{ steps.get-affected.outputs.affected_matrix }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Crucial para que Nx pueda comparar commits

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
